# Generated by Django 5.1.7 on 2025-03-24 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/')),
                ('mode', models.CharField(choices=[('cutting', 'Вырез'), ('engraving', 'Гравировка')], max_length=20)),
                ('material', models.CharField(max_length=100)),
                ('thickness', models.CharField(max_length=50)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('accepted', 'Принят'), ('in_progress', 'В процессе'), ('rejected', 'Отклонён')], default='waiting', max_length=20)),
                ('work', models.DecimalField(decimal_places=2, max_digits=10)),
                ('laser_work', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
